# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Booking_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(353, 268)
        MainWindow.setFixedSize(353, 268)             #---------------------------------------------------------
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setWindowTitle("T+2 Booking")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_b = QtWidgets.QPushButton(self.centralwidget)
        self.start_b.setGeometry(QtCore.QRect(50, 180, 93, 28))
        self.start_b.setObjectName("start_b")
        self.Pause_b = QtWidgets.QPushButton(self.centralwidget)
        self.Pause_b.setGeometry(QtCore.QRect(210, 180, 93, 28))
        self.Pause_b.setObjectName("Pause_b")
        self.First_Row = QtWidgets.QLineEdit(self.centralwidget)
        self.First_Row.setGeometry(QtCore.QRect(70, 120, 50, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.First_Row.sizePolicy().hasHeightForWidth())
        self.First_Row.setSizePolicy(sizePolicy)
        self.First_Row.setMaximumSize(QtCore.QSize(16777215, 16777215))



        icon = QtGui.QIcon()                                 #-----------------------------------------------------------------------------------
        icon.addPixmap(QtGui.QPixmap("logo1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(30, 28))

        self.First_Row.setObjectName("First_Row")
        self.Last_Row = QtWidgets.QLineEdit(self.centralwidget)
        self.Last_Row.setGeometry(QtCore.QRect(230, 120, 50, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Last_Row.sizePolicy().hasHeightForWidth())
        self.Last_Row.setSizePolicy(sizePolicy)
        self.Last_Row.setObjectName("Last_Row")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 90, 81, 21))
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 90, 81, 21))
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setObjectName("label_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 0, 315, 80))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.Status_label = QtWidgets.QLabel(self.groupBox_4)
        self.Status_label.setGeometry(QtCore.QRect(30, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Status_label.setFont(font)
        self.Status_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Status_label.setText("")
        self.Status_label.setObjectName("Status_label")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 90, 315, 71))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 170, 315, 51))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_4.raise_()
        self.groupBox_6.raise_()
        self.groupBox_5.raise_()
        self.start_b.raise_()
        self.Pause_b.raise_()
        self.First_Row.raise_()
        self.Last_Row.raise_()
        self.label.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 353, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        #MainWindow.setWindowTitle(_translate("MainWindow", "T+2 Booking"))

        self.start_b.setText(_translate("MainWindow", "Run"))
        self.Pause_b.setText(_translate("MainWindow", "Pause"))
        self.label.setText(_translate("MainWindow", "From Row"))
        self.label_2.setText(_translate("MainWindow", "To Row"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
