# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 272)
        MainWindow.setMinimumSize(QtCore.QSize(391, 272))
        MainWindow.setMaximumSize(QtCore.QSize(391, 272))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_b = QtWidgets.QPushButton(self.centralwidget)
        self.start_b.setGeometry(QtCore.QRect(50, 180, 93, 28))
        self.start_b.setObjectName("start_b")
        self.Pause_b = QtWidgets.QPushButton(self.centralwidget)
        self.Pause_b.setGeometry(QtCore.QRect(260, 180, 93, 28))
        self.Pause_b.setObjectName("Pause_b")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 0, 361, 80))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.Status_label = QtWidgets.QLabel(self.groupBox_4)
        self.Status_label.setGeometry(QtCore.QRect(50, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Status_label.setFont(font)
        self.Status_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Status_label.setText("")
        self.Status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Status_label.setObjectName("Status_label")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 90, 361, 71))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.Even_Rows = QtWidgets.QCheckBox(self.groupBox_5)
        self.Even_Rows.setGeometry(QtCore.QRect(10, 20, 111, 20))
        self.Even_Rows.setObjectName("Even_Rows")
        self.Odd_Rows = QtWidgets.QCheckBox(self.groupBox_5)
        self.Odd_Rows.setGeometry(QtCore.QRect(140, 20, 111, 20))
        self.Odd_Rows.setObjectName("Odd_Rows")
        self.All_Rows = QtWidgets.QCheckBox(self.groupBox_5)
        self.All_Rows.setGeometry(QtCore.QRect(260, 20, 111, 20))
        self.All_Rows.setObjectName("All_Rows")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 170, 361, 51))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_4.raise_()
        self.groupBox_6.raise_()
        self.groupBox_5.raise_()
        self.start_b.raise_()
        self.Pause_b.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Offline Orders"))
        self.start_b.setText(_translate("MainWindow", "Run"))
        self.Pause_b.setText(_translate("MainWindow", "Pause"))
        self.Even_Rows.setText(_translate("MainWindow", "Even Rows"))
        self.Odd_Rows.setText(_translate("MainWindow", "Odd Rows"))
        self.All_Rows.setText(_translate("MainWindow", "All Rows"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
